server:
  port: 8888
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
logging:
  level:
    org.springframework: debug
ctrip:
  security:
    oauth2:
      clients[0]:
        clientId: ctrip
        clientSecret: rezen
      clients[1]:
        clientId: test1
        clientSecret: test1
      clients[2]:
        clientId: test2
        clientSecret: test2
