server:
  port: 8888
spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
logging:
  level:
    org.springframework: debug
ctrip:
  security:
    oauth2:
      storeType: redis #或者jwt
#      jwtSigningKey: merryyou
      clients[0]:
        clientId: ctrip
        clientSecret: rezen
      clients[1]:
              clientId: merryyou
              clientSecret: merryyou
      clients[2]:
        clientId: test1
        clientSecret: test1
